package com.meditrack.domain.reminder

import com.meditrack.R

/**
 * The five tones that ship inside the APK.
 *
 * They exist because the previous design pointed the alert channel at the phone's own alarm ringtone
 * (`content://settings/system/alarm_alert`). On MIUI/HyperOS that URI is under the system's control: the
 * per-app notification style can replace or mute it, and then the reminder arrives with vibration and no
 * audible tone - reported from a Redmi running MIUI V140. A tone that lives in `res/raw` cannot be taken
 * away by the OS, which is what makes the reminder audible on vivo, Xiaomi, OPPO and everything else.
 *
 * Generated by `tools/generate_tones.py`; see that script for why they are synthesised rather than
 * downloaded (licensing).
 */
enum class ReminderTone(val label: String, val rawRes: Int) {
    BELL("清铃", R.raw.tone_1_bell),
    RISING("三音上行", R.raw.tone_2_rising),
    MARIMBA("柔和木琴", R.raw.tone_3_marimba),
    BEEP("双哔", R.raw.tone_4_beep),
    CHIME("渐强钟声", R.raw.tone_5_chime),
    ;

    companion object {
        val DEFAULT = BELL

        fun fromName(name: String?): ReminderTone =
            entries.firstOrNull { it.name == name } ?: DEFAULT
    }
}

/**
 * Channel ids for the audible reminder.
 *
 * The id has to change whenever the sound or the vibration setting changes, because Android freezes a
 * channel's sound at creation and silently ignores later updates. A user who picks a different tone
 * would otherwise keep hearing the old one forever - which is exactly the class of bug this whole
 * feature exists to fix.
 *
 * The id also encodes a **custom** tone (a file the user picked through the system picker) by a stable
 * hash of its URI, so the channel can carry that URI while still being distinguishable.
 *
 * Kept pure so the naming rules can be tested without a device.
 */
object AlertChannel {

    const val PREFIX = "meditrack_alert_"

    /** The channel this app shipped before tones were bundled; deleted on upgrade. */
    const val LEGACY_ALERT = "meditrack_reminder_alert"

    fun id(tone: ReminderTone, vibrationEnabled: Boolean, customSoundUri: String? = null): String {
        val sound = customSoundUri
            ?.takeIf { it.isNotBlank() }
            ?.let { "c" + Integer.toHexString(it.hashCode()) }
            ?: "t" + tone.ordinal
        val haptics = if (vibrationEnabled) "v" else "s"
        return "$PREFIX${sound}_$haptics"
    }

    fun isAlert(channelId: String?): Boolean = channelId?.startsWith(PREFIX) == true

    /**
     * Channels to remove once [keep] is the current one.
     *
     * Without this the system's per-app notification list grows an entry for every tone the user tries.
     */
    fun stale(existing: Collection<String>, keep: String): List<String> =
        existing.filter { (isAlert(it) || it == LEGACY_ALERT) && it != keep }
}
