"""
Generates the widget-picker preview drawable.

The preview is generated rather than hand-drawn so its geometry is derived from the same budget
`WidgetSizing` uses on the device: same padding steps, same header block, same row unit. A hand-drawn
preview drifts from the real widget the first time either changes, and a preview that lies is worse
than no preview - it is what the user picks the widget from.

Run from the project root:  python tools/make_widget_previews.py
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "app", "src", "main", "res", "drawable")

WIDTH = 250
CELL_DP = 70

# The launcher places the single widget at 4x2 (see targetCellWidth/Height in the metadata).
DEFAULT_ROWS = 2

# Mirrors WidgetSizing at the default font scale.
ROW_PADDING = 8.0
ROW_TEXT_BASE = 30.0
ROW_SPACING = 4.0
HEADER_CONTENT = 18.0
HEADER_GAP = 6.0
DEFAULT_ITEM_LIMIT = 4

ROW_UNIT = ROW_PADDING + ROW_TEXT_BASE + ROW_SPACING
HEADER_BLOCK = HEADER_CONTENT + HEADER_GAP

# Mirrors the light-launcher values in res/values/colors_widget.xml.
BG = "#FFFFFBF7"
TITLE = "#FF1B1C1E"
MUTED = "#FF5C5F66"
YELLOW = "#FF8A6100"
RED = "#FFB3261E"
BLUE = "#FF1D5FA8"
GREEN = "#FF1F7A45"
YELLOW_TINT = "#1A8A6100"
RED_TINT = "#1AB3261E"
TRANSPARENT = "#00000000"

# One entry per row, in the order the planner produces them: yellow (due within 30 minutes) first,
# then red (its time has passed), then the neutral and completed rows.
ROWS = [
    (YELLOW, YELLOW_TINT),
    (RED, RED_TINT),
    (BLUE, TRANSPARENT),
    (GREEN, TRANSPARENT),
]


def padding_for(height):
    if height >= 140:
        return 12
    if height >= 100:
        return 8
    return 4


def rounded_rect(x, y, w, h, r, color):
    """A rounded rectangle as a vector path, with the radius clamped to the smaller side."""
    r = max(0, min(r, w / 2, h / 2))
    return (
        f'    <path android:fillColor="{color}" android:pathData="'
        f"M{x + r},{y} h{w - 2 * r} a{r},{r} 0 0 1 {r},{r} v{h - 2 * r} "
        f"a{r},{r} 0 0 1 -{r},{r} h-{w - 2 * r} a{r},{r} 0 0 1 -{r},-{r} "
        f'v-{h - 2 * r} a{r},{r} 0 0 1 {r},-{r} z" />'
    )


def circle(cx, cy, r, color):
    return (
        f'    <path android:fillColor="{color}" android:pathData="'
        f'M{cx},{cy} m-{r},0 a{r},{r} 0 1,1 {2 * r},0 a{r},{r} 0 1,1 -{2 * r},0 z" />'
    )


def build():
    height = CELL_DP * DEFAULT_ROWS
    pad = padding_for(height)
    available = height - 2 * pad

    # Mirrors WidgetSizing.layoutFor at the default font scale. The dense single-line fallback is not
    # modelled: it only applies below ~50dp, and this preview is drawn at 140dp.
    show_header = int((available - HEADER_BLOCK) / ROW_UNIT) >= 1
    header_block = HEADER_BLOCK if show_header else 0.0
    usable = available - header_block

    rows_without_hint = max(1, int(usable / ROW_UNIT))
    row_limit = min(rows_without_hint, DEFAULT_ITEM_LIMIT)
    slot = usable / row_limit

    paths = [rounded_rect(0, 0, WIDTH, height, 16, BG)]

    if show_header:
        # A 16dp glyph beside the title, matching the composable.
        gy = pad + 3
        paths.append(circle(pad + 8, gy + 8, 5, BLUE))
        paths.append(rounded_rect(pad + 20, gy + 5, 46, 6, 3, TITLE))
        paths.append(rounded_rect(WIDTH - pad - 34, gy + 5, 34, 6, 3, MUTED))

    for i in range(row_limit):
        top = pad + header_block + i * slot
        band_h = slot - ROW_SPACING
        color, tint = ROWS[i % len(ROWS)]
        if tint != TRANSPARENT:
            paths.append(rounded_rect(pad, top, WIDTH - 2 * pad, band_h, 12, tint))

        cy = top + band_h / 2
        paths.append(circle(pad + 13, cy, 5, color))
        paths.append(circle(pad + 30, cy, 8, color))
        paths.append(rounded_rect(pad + 44, cy - 8, 92, 6, 3, TITLE))
        paths.append(rounded_rect(pad + 44, cy + 1, 56, 5, 2.5, MUTED))
        paths.append(rounded_rect(WIDTH - pad - 44, cy - 3, 38, 5, 2.5, color))

    body = "\n".join(paths)
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!--\n"
        f"  Widget picker preview: the single 4x{DEFAULT_ROWS} widget.\n\n"
        "  Generated by tools/make_widget_previews.py from the same layout budget WidgetSizing uses\n"
        "  on the device and the same colours res/values/colors_widget.xml defines, so the preview\n"
        "  cannot drift from the real widget. Do not edit by hand.\n"
        "-->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        f'    android:width="{WIDTH}dp"\n'
        f'    android:height="{height}dp"\n'
        f'    android:viewportWidth="{WIDTH}"\n'
        f'    android:viewportHeight="{height}">\n\n'
        f"{body}\n"
        "</vector>\n"
    )


def main():
    path = os.path.join(OUT_DIR, "ic_widget_preview.xml")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build())
    print(f"wrote {os.path.relpath(path, ROOT)}")


if __name__ == "__main__":
    main()
